#! /bin/bash

  # -e TORRENTING_PORT=6881 \
  # -v /var/media/HD1/download:/downloads \
  # -e PUID=1000 \
  # -e PGID=1000 \
  # -v /storage/.config/dockers/downloads:/downloads \

docker run -d \
  --name=qbittorrent \
  --network container:vpn \
  -e PUID=0 \
  -e PGID=0 \
  -e TZ=Europe/Paris \
  -e WEBUI_PORT=8082 \
  -v /storage/.config/dockers/qbittorrent:/config \
  -v /media/HD1/Downloads:/downloads \
  --restart unless-stopped \
  --platform linux/arm64 \
  lscr.io/linuxserver/qbittorrent:latest
