#!/bin/bash

# a copier dans ~/.local/share/nautilus/scripts
# + droits d'execution chmod +x

for fichier in "$@"; do
    if [[ -f "$fichier" ]]; then
        mkvmerge -J "$fichier" > "${fichier}.json"
        # notify-send "Export ffprobe" "Fichier exporté : ${fichier}.json"
    fi
done
