services:
  protonwire:
    image: ghcr.io/tprasadtp/protonwire:latest
    container_name: protonwire
    init: true
    environment:
      PROTONVPN_SERVER: "node-nl-96.protonvpn.net"  # NL-FREE#100070
      DEBUG: "0"
      KILL_SWITCH: "1"
      WIREGUARD_PRIVATE_KEY: "OIBT7avl5u6UWdDEJtq9CIKUW2wsLXXppNuH7tFmbkw="
      # IPCHECK_INTERVAL: 0
    cap_add:
      - NET_ADMIN
    sysctls:
      net.ipv4.conf.all.rp_filter: 2
      net.ipv6.conf.all.disable_ipv6: 1
    volumes:
      - type: tmpfs
        target: /tmp
        # Pas utile car la clé est dans la variable d'environnement
      # - type: bind
      #   source: private.key
      #   target: /etc/protonwire/private-key
      #   read_only: true
    ports:
      - 51820:51820/udp   # Port de WirreGuard
      - 8082:8082         # Port de qbittorrent
      - 9117:9117         # Port de jackett
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: service:protonwire
    environment:
      # - UMASK_SET=022 # Non nécessaire en principe
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - WEBUI_PORT=8082
      - TORRENTING_PORT=6881
    volumes:
      - ./qbittorrent:/config
      - ./downloads:/downloads
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    network_mode: service:protonwire
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - AUTO_UPDATE=true #optional
      # - RUN_OPTS= #optional
    volumes:
      - ./jackett:/config
      - ./jackett/blackhole:/downloads
    restart: unless-stopped
